apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
        - name: weather-service
          image: weather-service:latest
          ports:
            - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: weather-service